<?php

namespace Modules\Mall\Entities;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;

class ProductsCategories extends Model
{
    use NodeTrait;

    /*   public $data= [
        ['name' => 'Auto & Transportation', 'children' =>
            [
                ['name' => 'Engine Parts', 'children' => [
                    ['name' => 'Ignition Coils'],
                    ['name' => 'Ignition Line'],
                    ['name' => 'Spark Plug'],
                    ['name' => 'Cylinder Head'],
                    ['name' => 'Cylinder Head Gasket'],
                    ['name' => 'Timing Belt'],
                    ['name' => 'Crankshaft Pulley'],
                    ['name' => 'Tensioner'],
                    ['name' => 'Link'],
                    ['name' => 'Piston'],
                    ['name' => 'Camshaft'],
                    ['name' => 'Crankshaft'],
                    ['name' => 'Bush'],
                    ['name' => 'Injector'],
                    ['name' => 'Oxygen Sensor'],
                    ['name' => 'Intake Pressure'],
                    ['name' => 'Crankshaft Position Sensor'],
                    ['name' => 'Knock Sensor'],
                    ['name' => 'Throttle Valve Body Assembly'],
                    ['name' => 'Air Filter'],
                    ['name' => 'Oil Filter'],
                    ['name' => 'Turbocharger'],
                    ['name' => 'Clutch'],
                ]],
                ['name'=>'Transmission Parts','children'=>[
                    ['name'=>'Bearing'],
                    ['name'=>'Wind Wheel'],
                    ['name'=>'Differential'],
                    ['name'=>'Planet Carrier'],
                    ['name'=>'Intermediate Gear'],
                    ['name'=>'Multi-Wheel Gear Shaft'],
                    ['name'=>'Copper Sleeve'],
                    ['name'=>'Oil Pump Shaft'],
                    ['name'=>'The Electromagnetic Valve'],
                    ['name'=>'Torque Converter']
                ]],
                ['name'=>'Chassis Parts','children'=>[
                    ['name'=>'Torsion Beam'],
                    ['name'=>'Shock Absorber'],
                    ['name'=>'Axle'],
                    ['name'=>'Transmission Shaft'],
                    ['name'=>'Ten Bytes'],
                    ['name'=>'Brake Fluid'],
                    ['name'=>'Relay Valve'],
                    ['name'=>'Brake Pad'],
                    ['name'=>'Adjustment Arm'],
                    ['name'=>'Overflow Valve'],
                    ['name'=>'Booster'],
                    ['name'=>'Brake Drum'],
                    ['name'=>'Brake Disc'],
                    ['name'=>'ABS'],
                    ['name'=>'Turnover Mechanism'],
                    ['name'=>'Hand Brake Valve'],
                ]],
                ['name'=>'Body & Interiorand Exterior Parts','children'=>[
                    ['name'=>'Headlight'],
                    ['name'=>'Rear Tail Light'],
                    ['name'=>'Fog Light'],
                    ['name'=>'Front & Rear Bumpers'],
                    ['name'=>'Windshield'],
                    ['name'=>'Car Door'],
                    ['name'=>'Sunny Visor'],
                    ['name'=>'Door Bowl Trim'],
                    ['name'=>'Outer Handle Patch'],
                    ['name'=>'Fender'],
                    ['name'=>'Car Sticker'],
                    ['name'=>'Car Antenna'],
                    ['name'=>'Car Fog Light Box'],
                    ['name'=>'Car Light Eyebrow'],
                    ['name'=>'Car Taillight Frame'],
                    ['name'=>'Car Xenon Lamp'],
                    ['name'=>'Dvd Navigation'],
                    ['name'=>'Car Gps'],
                    ['name'=>'Car Mp3'],
                    ['name'=>'Car Stereo'],
                    ['name'=>'Car Horn'],
                    ['name'=>'Automotive Inverter'],
                    ['name'=>'Car Oxygen Bar'],
                    ['name'=>'Car Humidifier'],
                    ['name'=>'Car Reading Light'],
                    ['name'=>'Glue',
                        ['name'=>'Seat Cushion'],
                        ['name'=>'Waist Pad'],
                        ['name'=>'Carpet'],
                        ['name'=>'Seat Cover'],
                        ['name'=>'Sticker'],
                        ['name'=>'Keychain'],
                        ['name'=>'Decoration'],
                        ['name'=>'Hanging Ornament'],
                        ['name'=>'Curtain'],
                        ['name'=>'Insu lation Pot'],
                        ['name'=>'Solar Film'],
                        ['name'=>'Sun Block'],
                        ['name'=>'Anti-Theft Lock'],
                        ['name'=>'Gear Cover'],
                        ['name'=>'Airbag'],
                        ['name'=>'Car Hanger'],
                        ['name'=>'Insulation Cotton'],
                        ['name'=>'Tissue Box'],
                        ['name'=>'Door Edge Glue'],
                        ['name'=>'Phone Stand'],
                        ['name'=>'Gear Lock'],
                        ['name'=>'Self-Locking'],
                        ['name'=>'Seat Belt'],
                        ['name'=>'Barometer'],
                        ['name'=>'Thermometer'],
                        ['name'=>'Steering Wheel Cover'],
                        ['name'=>'Steering Wheel'],
                        ['name'=>'Instrument Panel'],
                        ['name'=>'Armrest Box'],
                        ['name'=>'Static Electricity Sticker'],
                        ['name'=>'Strip'],
                        ['name'=>'Anti-Collision Glue'],
                        ['name'=>'Perfume Holder'],
                    ]]],
                ['name'=>'Maintenance & Modification Supplies','children'=>[
                    ['name'=>'Car Hood'],
                    ['name'=>'Polishing Wax'],
                    ['name'=>'Instrument Wax'],
                    ['name'=>'Repair Wax'],
                    ['name'=>'Air Purifier'],
                    ['name'=>'Car Leather Care'],
                    ['name'=>'Car Rain Enemy'],
                    ['name'=>'Fog Enemy'],
                    ['name'=>'Front And Rear Bars'],
                    ['name'=>'Big Encirclement'],
                    ['name'=>'High Tail'],
                    ['name'=>'Opening Bonnet'],
                    ['name'=>'Window Visor'],
                    ['name'=>'Hid Xenon Headlights'],
                    ['name'=>'Headlight Decorative Panel'],
                    ['name'=>'Sticker'],
                ]],
                ['name'=>'Auto Repair Tool','children'=>[
                    ['name'=>'Jack'],
                    ['name'=>'Mist Machine'],
                    ['name'=>'Washing Turbine'],
                    ['name'=>'Electric Circular Saw'],
                    ['name'=>'Air Gun'],
                    ['name'=>'Polisher'],
                    ['name'=>'Spray Gun'],
                    ['name'=>'Wind Gun'],
                    ['name'=>'Waxing Machine'],
                    ['name'=>'Fighting Machine'],
                    ['name'=>'Finishing Machine'],
                    ['name'=>'Hot Air Gun'],
                    ['name'=>'Sprayer'],
                    ['name'=>'Hydraulic Jacks'],
                    ['name'=>'Snow Chain'],
                    ['name'=>'Anti-Skid Chain Fitting'],
                    ['name'=>'Tire Locator'],
                    ['name'=>'Lift'],
                    ['name'=>'Vulcanizer'],
                    ['name'=>'Spray Booth'],
                    ['name'=>'Grilled Tire Machine'],
                    ['name'=>'Balance Machine'],
                    ['name'=>'Car Washer'],
                    ['name'=>'Paint Room'],
                    ['name'=>'Bake Lamp'],
                    ['name'=>'Automatic Car Washing Machine'],
                    ['name'=>'Double Column Lift'],
                    ['name'=>'Car Lift']
                ]],
            ]
        ],
        ['name'=>'Construction','children'=>
            [
                ['name'=>'Home Improvement Building Materials','children'=>[
                        ['name'=>'Floors'],
                        ['name'=>'Doors & Windows'],
                        ['name'=>'Floor Tile'],
                        ['name'=>'Wallpaper'],
                        ['name'=>'Home Improvement Plate'],
                        ['name'=>'Suspended Ceilings'],
                        ['name'=>'Wire & Cable'],
                        ['name'=>'Stone'],
                        ['name'=>'Diatom Mud'],
                        ['name'=>'Glass'],
                        ['name'=>'Removable Cover Plate'],
                        ['name'=>'Plumbing Hardware'],
                        ['name'=>'Home Improvement Main Material'],
                        ['name'=>'Pipe Fittings'],
                        ['name'=>'Building Ceramic'],
                        ['name'=>'Electrical Equipment']
                    ]],
                ['name'=>'Pipe Fittings','children'=>[
                        ['name'=>'Bellows'],
                        ['name'=>'Compensator'],
                        ['name'=>'Tee'],
                        ['name'=>'Head'],
                        ['name'=>'Power Tube'],
                        ['name'=>'Plastic Tube'],
                        ['name'=>'Galvanized Tube'],
                        ['name'=>'Metal Hose'],
                        ['name'=>'Abnormity Tube'],
                        ['name'=>'Double Wall Corrugated Pipe'],
                        ['name'=>'Pe Bellows'],
                        ['name'=>'Rubber Bellows'],
                        ['name'=>'Single Wall Bellows'],
                        ['name'=>'Steel Belt Bellows'],
                        ['name'=>'Plastic Bellows'],
                    ]],
                ['name'=>'Plate','children'=>[
                        ['name'=>'Steel Plate'],
                        ['name'=>'Fireproof Board'],
                        ['name'=>'Low Alloy Plate'],
                        ['name'=>'Cold Rolled Steel'],
                        ['name'=>'Coated Steel'],
                        ['name'=>'Galvanized Steel'],
                        ['name'=>'Painted Steel'],
                        ['name'=>'Steel'],
                        ['name'=>'Angle Channel Steel'],
                        ['name'=>'Decoiled Steel Sheet'],
                        ['name'=>'Galvanized Coil'],
                        ['name'=>'Checkered Steel Plate'],
                        ['name'=>'Galvanized Sheet'],
                        ['name'=>'Polystyrene Board'],
                        ['name'=>'Galvanized Steel Pipe'],
                        ['name'=>'Galvanized Strip'],
                    ]],
                ['name'=>'Building Materials','children'=>[
                        ['name'=>'Door'],
                        ['name'=>'Windows'],
                        ['name'=>'Ladder'],
                        ['name'=>'Glue'],
                        ['name'=>'Wood'],
                        ['name'=>'Plumbing'],
                        ['name'=>'Stone'],
                        ['name'=>'Masonry'],
                        ['name'=>'Guardrail'],
                        ['name'=>'Pipe'],
                        ['name'=>'Steel'],
                        ['name'=>'Glass'],
                        ['name'=>'Ceiling'],
                        ['name'=>'Grouting'],
                        ['name'=>'Color Steel'],
                        ['name'=>'Landscape'],
                        ['name'=>'Removable Cover Plate'],
                        ['name'=>'Door & Window Hardware'],
                        ['name'=>'Construction Materials'],
                        ['name'=>'Metal Building Materials'],
                    ]],

            ]],
        ['name' => 'Home Furniture', 'children' =>
            [['name' => 'Kitchen & Dining Utensils', 'children' =>
                [
                    ['name' => 'Stainless Steel Dish Rack'],
                    ['name' => 'Skinning & Slicing Machine'],
                    ['name' => 'Mixer'],
                    ['name' => 'Covered Bowl'],
                    ['name' => 'Plate'],
                    ['name' => 'Baking Utensils'],
                    ['name' => 'Barbecue Utensils'],
                    ['name' => 'Bar Equipment'],
                ]
            ],
                ['name' => 'Home Decoration', 'children' => [
                    ['name' => 'Wallpaper'],
                    ['name' => 'Curtain'],
                    ['name' => 'Carpet'],
                    ['name' => 'Vase'],
                    ['name' => 'Mirror'],
                    ['name' => 'Decorative Paintings'],
                    ['name' => 'Picture Frame'],
                    ['name' => 'Photo Frame / Photo Frame'],
                    ['name' => 'Wall Decoration (Wall Sticker)'],
                    ['name' => 'Fridge Magnet'],
                    ['name' => 'Light Strip'],
                    ['name' => 'Clock'],
                    ['name' => 'Ceramic Ornaments'],
                    ['name' => 'Wooden Ornaments'],
                    ['name' => 'Resin Decoration'],
                    ['name' => 'A Gift Made-To-Order'],
                ]],
                ['name' => 'Household Debris', 'children' => [
                    ['name' => 'Multifunctional Hang'],
                    ['name' => 'Mosquito Net'],
                    ['name' => 'Apron'],
                    ['name' => 'Microwave Oven Glove'],
                    ['name' => 'Sewing Supplies'],
                ]],
                ['name' => 'Household Storage & Collection Devices', 'children' => [
                    ['name' => 'Shelf'],
                    ['name' => 'Store Content Box'],
                ]],
                ['name' => 'Household Cleaning Tools & Accessories', 'children' => [
                    ['name' => 'Ashtray'],
                    ['name' => 'Laundry Hood'],
                    ['name' => 'Multi-Function Brush'],
                    ['name' => 'Double-Sided Sticker'],
                ]],
                ['name' => 'Pet Supplies', 'children' => [
                    ['name' => 'Pet Supplies (Pet Nail Trimmer)'],
                    ['name' => 'Pet Food'],
                    ['name' => 'Fish Tank'],
                    ['name' => 'Pet Toy (Tooth Cleaning Ball)'],
                ]],
                ['name' => 'Furniture', 'children' => [
                    ['name' => 'Kitchen Furniture'],
                    ['name' => 'Bathroom Furniture'],
                    ['name' => 'Bedroom Furniture'],
                    ['name' => 'Living Room Furniture'],
                    ['name' => 'Study Furniture'],
                    ['name' => 'Outdoor Furniture'],
                    ['name' => 'Small Furniture'],
                    ['name' => 'Furniture Component'],
                ]],
                ['name' => 'Home Textiles', 'children' => [
                    ['name' => 'Tablecloth'],
                    ['name' => 'Chair Cover'],
                    ['name' => 'Sofa Cover'],
                    ['name' => 'Core Class'],
                    ['name' => 'Lazy Blanket'],
                    ['name' => 'Four-Piece Set'],
                    ['name' => 'Mattress'],
                    ['name' => 'Sheets'],
                    ['name' => 'Quilt'],
                ]],
                ['name' => 'Others', 'children' => [
                    ['name' => 'Rain Boots'],
                    ['name' => 'Raincoat'],
                    ['name' => 'Earplugs'],
                    ['name' => 'Anti-Mosquito Repellent Products'],
                    ['name' => 'Carving Tool'],
                    ['name' => 'Nail Clipper'],
                    ['name' => 'Epilator'],
                    ['name' => 'Decorative Keychain'],
                    ['name' => 'Gift Box'],
                    ['name' => 'Other'],
                ]],
            ]
        ],
        ['name' => 'Household Appliances', 'children' =>
            [
                ['name' => 'Household Appliances Accessories', 'children' => [
                    ['name' => 'Motor'],
                    ['name' => 'Wire'],
                    ['name' => 'Temperature Control'],
                    ['name' => 'Air Pressure Switch'],
                    ['name' => 'Fire Platoon'],
                    ['name' => 'Socket'],
                    ['name' => 'Plug'],
                    ['name' => 'Drain Pipe'],
                    ['name' => 'Filter Bag'],
                    ['name' => 'Spring'],
                    ['name' => 'Filter'],
                    ['name' => 'Seal Ring'],
                    ['name' => 'Pipeline'],
                    ['name' => 'Small Generator'],
                ]],
                ['name' => 'Home Appliances', 'children' => [
                    ['name' => 'Bluetooth Speaker'],
                    ['name' => 'Sound'],
                    ['name' => 'Water Purifier'],
                    ['name' => 'Air Conditioning'],
                    ['name' => 'Refrigerator'],
                    ['name' => 'Rice Cooker'],
                    ['name' => 'Electric Fan'],
                    ['name' => 'Lampblack Machine'],
                    ['name' => 'Juicer'],
                    ['name' => 'Multi-Function Cooking Ma'],
                    ['name' => 'Massager'],
                    ['name' => 'Mosquito Lamp'],
                    ['name' => 'Humidifier'],
                    ['name' => 'Air Purifier'],
                    ['name' => 'Sweeping Robot'],
                    ['name' => 'Electric Toothbrush'],
                    ['name' => 'Hair Dryer'],
                    ['name' => 'Vacuum Cleaner'],
                    ['name' => 'Air-Conditioning Fan'],
                ]],
            ]],
        ['name' => 'Lights', 'children' =>
            [
                ['name' => 'LED Indoor Light Fixture', 'children' => [
                    ['name' => 'Led Light Strip'],
                    ['name' => 'Led Downlight'],
                    ['name' => 'Led Panel Light'],
                    ['name' => 'Led Ceiling Light'],
                    ['name' => 'Led Spotlight'],
                    ['name' => 'Led High Bay Light'],
                ]],
                ['name' => 'LED Display', 'children' => [
                    ['name' => 'Led Outdoor Display'],
                    ['name' => 'Led Indoor Display'],
                    ['name' => 'Display Control Card'],
                    ['name' => 'Display Control Card'],
                    ['name' => 'Led Curtain Wall Screen'],
                    ['name' => 'Led Advertising Mach'],
                    ['name' => 'Led Dot Matrix'],
                ]],
                ['name' => 'Outdoor Lighting', 'children' => [
                    ['name' => 'Led Outdoor Lighting'],
                    ['name' => 'Led Street Light'],
                    ['name' => 'Led Flood Light'],
                    ['name' => 'Solar Light'],
                    ['name' => 'Landscape Light'],
                    ['name' => 'High Pole Light'],
                ]],
                ['name' => 'Lighting Fixture', 'children' => [
                    ['name' => 'Ceiling Light'],
                    ['name' => 'Chandelier'],
                    ['name' => 'Night Light'],
                    ['name' => 'Downlight'],
                    ['name' => 'Wall Lamp'],
                    ['name' => 'Grille Light'],
                ]],
                ['name' => 'Electronic Component', 'children' => [
                    ['name' => 'Integrated Circuit'],
                    ['name' => 'Connector'],
                    ['name' => 'Capacitor'],
                    ['name' => 'Sensor'],
                    ['name' => 'Inductor'],
                    ['name' => 'Diode'],
                ]],
            ]],
        ['name' => 'Hotel Products', 'children' =>
            [
                ['name' => 'Kitchen Supplies', 'children' => [
                    ['name' => 'Ceramic Table'],
                    ['name' => 'Glassware'],
                    ['name' => 'Stainless Steel Products'],
                    ['name' => 'Placemat Tablecloth'],
                    ['name' => 'Bamboo And Wood Products'],
                    ['name' => 'Ceramic Tableware'],
                    ['name' => 'Gold And Silver Tableware'],
                    ['name' => 'Melamine Products'],
                    ['name' => 'Steaming Wok'],
                    ['name' => 'Tool'],
                    ['name' => 'Soup Spoon'],
                    ['name' => 'Oil Can'],
                    ['name' => 'Kettle'],
                    ['name' => 'Teapot'],
                    ['name' => 'Coffee Pot'],
                    ['name' => 'Sink'],
                ]],
                ['name' => 'Room supplies', 'children' => [
                    ['name' => 'Telephone'],
                    ['name' => 'Electric Kettle'],
                    ['name' => 'Hair Dryer'],
                    ['name' => 'Electric Iron'],
                    ['name' => 'Human Body Electronic Scale'],
                    ['name' => 'Digital Product'],
                    ['name' => 'Air Purifier'],
                    ['name' => 'Soap Dispenser'],
                    ['name' => 'Special Foam'],
                    ['name' => 'Fragrance Machine'],
                    ['name' => 'Freshener'],
                    ['name' => 'Paper Towel Holder'],
                    ['name' => 'Toilet Accessory'],
                    ['name' => 'Soap Dish'],
                    ['name' => 'Disposable Items'],
                    ['name' => 'Towel'],
                ]],
                ['name' => 'Hotel Decoration', 'children' => [
                    ['name' => 'Wallpaper'],
                    ['name' => 'Carpet'],
                    ['name' => 'Mural'],
                ]],
                ['name' => 'Room Furniture', 'children' => [
                    ['name' => 'Cabinet'],
                    ['name' => 'Bed'],
                    ['name' => 'Table'],
                    ['name' => 'Sofa'],
                    ['name' => 'Chair'],
                ]],
                ['name' => 'Hotel Tools', 'children' => [
                    ['name' => 'Vacuum Cleaner'],
                    ['name' => 'Scrubber'],
                    ['name' => 'Water Suction Machine'],
                    ['name' => 'Brushing Machine'],
                    ['name' => 'Telephone'],
                    ['name' => 'Sundries Basket'],
                    ['name' => 'Indicator'],
                    ['name' => 'Trolley'],
                    ['name' => 'Wine Cart'],
                    ['name' => 'Umbrella Stand'],
                    ['name' => 'Ash Bucket'],
                ]],
            ]],
        ['name' => 'Fabric Material', 'children' =>
            [
                ['name' => 'Fabric', 'children' => [
                    ['name' => 'Non-Woven Fabric'],
                    ['name' => 'Knitted Fabric'],
                    ['name' => 'Fabric'],
                    ['name' => 'Polyester Fabric'],
                    ['name' => 'Polyester Cotton Fabric'],
                    ['name' => 'Composite Fabric'],
                    ['name' => 'Mesh Cloth'],
                    ['name' => 'Canvas'],
                    ['name' => 'Denim Fabric'],
                    ['name' => 'Flax'],
                    ['name' => 'Not Down'],
                    ['name' => 'Sweat'],
                    ['name' => 'Corduroy Cloth'],
                    ['name' => 'Corduroy cloth'],
                ]],
                ['name' => 'Textile', 'children' => [
                    ['name' => 'Yarn Weave'],
                    ['name' => 'Calico'],
                    ['name' => 'Needle Punched Nonwoven'],
                    ['name' => 'Spunlaced Nonwoven'],
                    ['name' => 'Textile Nonwoven'],
                    ['name' => 'Packaging Textiles'],
                    ['name' => 'Industrial Textiles']
                ]],
                ['name' => 'Leather', 'children' => [
                    ['name' => 'Pig Leather'],
                    ['name' => 'Cow Leather'],
                    ['name' => 'Sheep Leather'],
                    ['name' => 'Horse Leather'],
                    ['name' => 'Artificial Leather'],
                    ['name' => 'Synthetic Leather'],
                    ['name' => 'Artificial Fur'],
                ]],
                ['name' => 'Clothing Accessories', 'children' => [
                    ['name' => 'Lace Lace'],
                    ['name' => 'Tassels And Spikes'],
                    ['name' => 'Drawnwork Embroidery'],
                    ['name' => 'Sewing Thread And Cord'],
                    ['name' => 'Cotton Yarn'],
                    ['name' => 'Chemical Fiber Yarn'],
                    ['name' => 'Blended Yarn'],
                    ['name' => 'Ribbon'],
                    ['name' => 'Zipper'],
                    ['name' => 'Lace'],
                    ['name' => 'Trademark'],
                    ['name' => 'Button'],
                ]],
                ['name' => 'Chemical Fiber', 'children' => [
                    ['name' => 'Polypropylene'],
                    ['name' => 'Fiberglass Belt'],
                    ['name' => 'Glass Cloth'],
                    ['name' => 'Mesh Cloth'],
                    ['name' => 'Aramid Cloth'],
                    ['name' => 'Elastic Wire'],
                    ['name' => 'Polyester Yarn'],
                    ['name' => 'Fiberglass Cloth'],
                    ['name' => 'Glass Cloth'],
                    ['name' => 'Glass Fiber'],
                    ['name' => 'Crack Resistant Fiber'],
                    ['name' => 'Tenon Fiber'],
                    ['name' => 'Frp Cloth'],
                    ['name' => 'Pipe Wrap'],
                    ['name' => 'Polypropylene Fibers'],
                ],
                ]]],
        ['name' => 'Metal Parts & Tools',
            'children' => [
                ['name' => 'Hardware Tools', 'children' => [
                    ['name' => 'Electrical Tools'],
                    ['name' => 'Pneumatic Tool'],
                    ['name' => 'Hand Operated Tools'],
                    ['name' => 'Portfolio Tools'],
                    ['name' => 'Cutting Tool'],
                    ['name' => 'Lock'],
                    ['name' => 'Electric Drill'],
                ]],
                ['name' => 'Hardware Accessories', 'children' => [
                    ['name' => 'Spring'],
                    ['name' => 'Gear'],
                    ['name' => 'Bearing'],
                    ['name' => 'Sprocket'],
                    ['name' => 'Roller'],
                    ['name' => 'Shackle'],
                    ['name' => 'Pulley'],
                    ['name' => 'Connector'],
                    ['name' => 'Valve'],
                    ['name' => 'Casters'],
                    ['name' => 'Universal Wheel'],
                    ['name' => 'Transmission Parts'],
                    ['name' => 'Duct'],
                    ['name' => 'Heat Sink'],
                    ['name' => 'Diesel Grinding'],
                ]],
                ['name' => 'Daily Hardware', 'children' => [
                    ['name' => 'Pliers'],
                    ['name' => 'Wrench'],
                    ['name' => 'Hammer'],
                    ['name' => 'Electric Drill'],
                    ['name' => 'Hydraulic Clamp'],
                    ['name' => 'Fall Arrester'],
                    ['name' => 'Wire Cutter'],
                    ['name' => 'Pipe Clamp'],
                    ['name' => 'Quick Connector'],
                ]],
                ['name' => 'Plumbing Hardware', 'children' => [
                    ['name' => 'Faucet'],
                    ['name' => 'Floor Drain'],
                    ['name' => 'Water Collector'],
                    ['name' => 'Water Valve'],
                    ['name' => 'Towel Rack'],
                    ['name' => 'Shower'],
                ]],
                ['name' => 'Door &window hardwar', 'children' => [
                    ['name' => 'Door Stopper'],
                    ['name' => 'Door Touch'],
                    ['name' => 'Door Lock'],
                    ['name' => 'Smart Door Lock'],
                    ['name' => 'Plastic Profile'],
                    ['name' => 'Door Handle'],
                ]],
                ['name' => 'Fastener', 'children' => [
                    ['name' => 'Bolt'],
                    ['name' => 'Screw'],
                    ['name' => 'Screw'],
                    ['name' => 'Nut'],
                    ['name' => 'Washer'],
                    ['name' => 'Electrical Tape'],
                    ['name' => 'Hex Nuts'],
                    ['name' => 'Shaped Nut'],
                    ['name' => 'Locknut'],
                    ['name' => 'Flange Nut'],
                    ['name' => 'Stainless Steel Nut'],
                    ['name' => 'High Strength Nut'],
                    ['name' => 'Hex Bolts'],
                    ['name' => 'Stud'],
                    ['name' => 'Anchor Bolt'],
                    ['name' => 'U-Bolt'],
                ]],
            ]],
        ['name' => 'Packaging', 'children' =>
            [['name' => 'Non-Plastic Packaging', 'children' =>
                [
                        ['name' => 'Paper Bag'],
                        ['name' => 'Paper Cups'],
                        ['name' => 'Cartons'],
                        ['name' => 'Carton'],
                        ['name' => 'Wooden Pallets'],
                        ['name' => 'Wooden Case'],
                ]
                ]
            ]],
        ['name' => 'Idle Item', 'children' =>
            [['name' => 'Idle Item', 'children' => [
                ['name' => 'Clothes'],
                ['name' => 'Mobile Phone'],
                ['name' => 'Electrical Appliances'],
                ['name' => 'Furniture'],
            ]]]],
        ['name' => 'Food & Beverage / Agriculture',
            'children' => [
                ['name' => 'Fruit', 'children' => [
                    ['name' => 'Orangic Fruit'],
                    ['name' => 'Fresh Fruit']]],
                ['name'=>'Vegetable','children'=>[
                    ['name'=>'Garlic']
                ]]
            ]]
    ];

    public function rebuild(Request $request)
    {
        $data = ProductsCategories::rebuildTree($this->data);
        $data = ProductsCategories::get()->toTree()->toArray();
        dd($data);
    }
    */

    protected $table = 'products_categories';

    protected $fillable = [
        'id','name','_lft','_rgt','parent_id','sort'
    ];

    protected $hidden = [
        '_lft', '_rgt','parent_id',
    ];

}